#pragma once
#include <zg/Scene.hpp>
zg::SceneCreateInfo EditorSceneFactory();
// struct EditorScene : Scene
// {
// 	glm::vec4 editorClearColor = {0.2, 0.2, 0.2, 1};
// 	float toolbarHeight;
// 	float bottomTabsHeight;
// 	zgfilesystem::File robotoRegularFile;
// 	fonts::freetype::FreetypeFont robotoRegularFont;
// 	Window* gameWindowPointer = nullptr;
// 	Window* codeWindowPointer = nullptr;
// 	float gameWindowBorderWidth;
// 	float gameWindowWidth;
// 	float gameWindowHeight;
// 	float gameWindowX;
// 	float gameWindowY;
// 	float codeWindowWidth;
// 	float codeWindowHeight;
// 	float codeWindowX;
// 	float codeWindowY;
// 	glm::vec4 toolbarColor;
// 	Entity* toolbar;
// 	Entity* bottomTabsBar;
// 	Entity* status;
// 	glm::vec4 gameWindowBorderColor = {0.4, 0.4, 0.7, 1};
// 	glm::vec4 gameWindowHoveredBorderColor = {0.7, 0.4, 0.4, 1};
// 	glm::vec4 gameWindowActiveBorderColor = {1, 0, 0, 1};
// 	Entity* gameWindowBorder;
// 	Entity* sceneGraphPanelMenu;
// 	float resourcePanelMenuHeight;
// 	Entity* resourcePanelMenu;
// 	Entity* resourceConsole;
// 	Entity* resourceAssetBrowser;
// 	size_t assetTabID = 0;
// 	Entity* resourcePanelTabs;
// 	size_t performanceTabID = 0;
// 	Entity* activeResourcePanelEntity = 0;
// 	UniqueIdentifier resizeID = 0;
// 	UniqueIdentifier gameWindowBorderHoverID = 0;
// 	UniqueIdentifier gameWindowBorderPressID = 0;
// 	UniqueIdentifier gameWindowESCPressID = 0;
// 	float dialogWidth;
// 	float dialogHeight;
// 	float closeNewDialogButtonWidth;
// 	float closeNewDialogButtonHeight;
// 	float okayNewDialogButtonWidth;
// 	float okayNewDialogButtonHeight;
// 	float closeOpenDialogButtonWidth;
// 	float closeOpenDialogButtonHeight;
// 	float okayOpenDialogButtonWidth;
// 	float okayOpenDialogButtonHeight;
// 	Entity* closeNewDialogButton;
// 	Entity* okayNewDialogButton;
// 	Entity* newProjectNameInput;
// 	Entity* newProjectDirectoryInput;
// 	Entity* newProjectDialog;
// 	Entity* closeOpenDialogButton;
// 	Entity* okayOpenDialogButton;
// 	Entity* openProjectDirectoryInput;
// 	Entity* openProjectDialog;
// 	Entity* activeDialog;
// 	std::shared_ptr<hs::Hotswapper> hotswapper;
// 	Project project;
// 	void(*OnLoad)(Window&) = 0;
// 	bool loaded = false;
// 	inline static std::filesystem::path programDirectoryPath = zgfilesystem::File::getProgramDirectoryPath();
// 	explicit EditorScene(Window& window);
// 	~EditorScene() override;
// 	void onEntityAdded(const Entity& entity);
// 	void setupGameWindow();
// 	void setupCodeWindow();
// 	void minimizeWindows();
// 	void removeActiveResourceEntity() const;
// 	void setupToolbarOptions();
// 	void newProject(std::string_view projectName, std::string_view projectDirectory);
// 	void openProject(std::string_view projectDirectory);
// };