set(ffmpeg_BINARY_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/ffmpeg-build")
set(glm_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/glm-src")
set(freetype_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/freetype-src")
set(bvh_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/bvh-src")
set(lunasvg_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/lunasvg-src")
set(plutovg_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/plutovg-src")
set(stb_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/stb-src")
set(miniaudio_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/miniaudio-src")
set(openssl_INC_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/openssl-build/include")
set(exprtk_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/exprtk-src")
set(boost_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/boost-src")
set(jolt_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/jolt-src")
set(ttf2mesh_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/ttf2mesh-src")
set(assimp_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/assimp-src")
set(assimp_BUILD_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/assimp-build")
set(vhacd_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/vhacd-src")
set(rtmidi_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/rtmidi-src")
set(tinyfiledialogs_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/tinyfiledialogs-src")
set(tracy_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/tracy-src")
set(cgal_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/cgal-install")
set(mc33_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/mc33-src")
set(msdf_atlas_gen_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/msdf_atlas_gen-src")
set(png_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/png-src")

set(CPACK_COMPONENT_HEADERS_DESCRIPTION "Zeungine Core & Dependency Headers")
set(CPACK_COMPONENT_HEADERS_GROUP "Zeungine")

# zg first
install(DIRECTORY ${ZG_SRC_ABS}/include/zg DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)

set(CPACK_COMPONENT_CMAKECONFIG_DESCRIPTION "Zeungine CMake Configuration")
set(CPACK_COMPONENT_CMAKECONFIG_GROUP "Zeungine")
install(FILES ../ZeungineConfig.cmake ../PlatformSetup.cmake ../Options.cmake ../Targets.cmake DESTINATION ${ZG_SHR_INSTALL_PREFIX}
    PERMISSIONS WORLD_READ OWNER_READ GROUP_READ
    COMPONENT CMakeConfig)

# png
install(FILES ${png_SOURCE_DIR}/png.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS WORLD_READ OWNER_READ GROUP_READ
    COMPONENT Headers)
# msdf_atlas_gen

install(FILES ${msdf_atlas_gen_SOURCE_DIR}/msdfgen/msdfgen.h ${msdf_atlas_gen_SOURCE_DIR}/msdfgen/msdfgen-ext.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS WORLD_READ OWNER_READ GROUP_READ
    COMPONENT Headers)

install(FILES ${msdf_atlas_gen_SOURCE_DIR}/msdfgen/msdfgen-config.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}/msdfgen
    PERMISSIONS WORLD_READ OWNER_READ GROUP_READ
    COMPONENT Headers)

install(DIRECTORY ${msdf_atlas_gen_SOURCE_DIR}/msdf-atlas-gen
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    COMPONENT Headers
    FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp"
    PERMISSIONS WORLD_READ OWNER_READ GROUP_READ)

# mc33
install(FILES ${mc33_SOURCE_DIR}/include/MC33.h DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS WORLD_READ OWNER_READ GROUP_READ
    COMPONENT Headers)

# tracy
if(ENABLE_TRACY)
    install(DIRECTORY ${tracy_SOURCE_DIR}/public/client
        DESTINATION ${ZG_INC_INSTALL_PREFIX}/tracy COMPONENT Headers
        FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp")
    install(DIRECTORY ${tracy_SOURCE_DIR}/public/common
        DESTINATION ${ZG_INC_INSTALL_PREFIX}/tracy COMPONENT Headers
        FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp")
    install(FILES
            ${tracy_SOURCE_DIR}/public/libbacktrace/backtrace.hpp
            ${tracy_SOURCE_DIR}/public/libbacktrace/config.h
            ${tracy_SOURCE_DIR}/public/libbacktrace/filenames.hpp
            ${tracy_SOURCE_DIR}/public/libbacktrace/internal.hpp
        DESTINATION ${ZG_INC_INSTALL_PREFIX}/tracy/libbacktrace COMPONENT Headers
        PERMISSIONS OWNER_READ GROUP_READ WORLD_READ)
    install(DIRECTORY ${tracy_SOURCE_DIR}/public/tracy
        DESTINATION ${ZG_INC_INSTALL_PREFIX}/tracy COMPONENT Headers
        FILES_MATCHING PATTERN "*.h" PATTERN "*.hpp")
endif()

# tinyfiledialogs
install(FILES ${tinyfiledialogs_SOURCE_DIR}/tinyfiledialogs.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT Headers)

# rtmidi
install(FILES ${rtmidi_SOURCE_DIR}/RtMidi.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT Headers)

# VHACD
install(FILES ${vhacd_SOURCE_DIR}/include/VHACD.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT Headers)

# assimp
install(DIRECTORY ${assimp_SOURCE_DIR}/include/assimp
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    COMPONENT Headers
    FILES_MATCHING
    PATTERN "*.h"
    PATTERN "*.hpp"
    PATTERN "*.inl"
    PATTERN "*.inc")
install(DIRECTORY ${assimp_BUILD_DIR}/include/assimp
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    COMPONENT Headers
    FILES_MATCHING
    PATTERN "*.h")

# ttf2mesh
install(FILES ${ttf2mesh_SOURCE_DIR}/ttf2mesh.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT Headers)

# svg
install(FILES ${lunasvg_SOURCE_DIR}/include/lunasvg.h ${plutovg_SOURCE_DIR}/include/plutovg.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT Headers)

# jolt includes
install(DIRECTORY ${jolt_SOURCE_DIR}/Jolt
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    COMPONENT Headers
    FILES_MATCHING
    PATTERN "*.h"
    PATTERN "*.hpp"
    PATTERN "*.inl"
    PATTERN "*.inc")

# boost includes
if(INSTALL_BOOST)
    file(GLOB BOOST_INCLUDES "${boost_SOURCE_DIR}/libs/*/include/boost")
    list(FILTER BOOST_INCLUDES EXCLUDE REGEX "^${boost_SOURCE_DIR}/libs/python/include/boost$")
    list(FILTER BOOST_INCLUDES EXCLUDE REGEX "^${boost_SOURCE_DIR}/libs/graph_parallel/include/boost$")
    list(FILTER BOOST_INCLUDES EXCLUDE REGEX "^${boost_SOURCE_DIR}/libs/stacktrace/include/boost$")
    list(FILTER BOOST_INCLUDES EXCLUDE REGEX "^${boost_SOURCE_DIR}/libs/mpi/include/boost$")

    foreach(dir ${BOOST_INCLUDES})
        install(DIRECTORY "${dir}" DESTINATION ${ZG_INC_INSTALL_PREFIX}
            FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
            DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
    endforeach()
endif()

# openssl includes
if(NOT MACOS AND NOT LINK_SYS_OPENSSL)
    install(DIRECTORY "${openssl_INC_DIR}/openssl" DESTINATION ${ZG_INC_INSTALL_PREFIX}
        FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
        DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
endif()

# ffmpeg includes

install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavcodec" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavdevice" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavfilter" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavformat" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavutil" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libswresample" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libswscale" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
# datsit frrom ffmpeg


# angel headers

install(DIRECTORY ${ZG_SRC_ABS}/include/angle DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY ${ZG_SRC_ABS}/include/GL DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY ${ZG_SRC_ABS}/include/glad DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY ${ZG_SRC_ABS}/include/shaderc DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY ${ZG_SRC_ABS}/include/SwiftShader DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY ${ZG_SRC_ABS}/include/wayland DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY ${glm_SOURCE_DIR}/glm DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(DIRECTORY ${freetype_SOURCE_DIR}/include/freetype DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)
install(FILES ${freetype_SOURCE_DIR}/include/ft2build.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT Headers)
install(DIRECTORY ${bvh_SOURCE_DIR}/src/bvh DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT Headers)

install(FILES ${stb_SOURCE_DIR}/stb_image.h ${stb_SOURCE_DIR}/stb_image_write.h ${stb_SOURCE_DIR}/stb_image_resize2.h
    ${stb_SOURCE_DIR}/stb_hexwave.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT Headers)

install(FILES ${miniaudio_SOURCE_DIR}/miniaudio.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT Headers)

install(FILES ${exprtk_SOURCE_DIR}/exprtk.hpp DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT Headers)