set(ffmpeg_BINARY_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build/_deps/ffmpeg-build")
set(glm_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build/_deps/glm-src")
set(freetype_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build/_deps/freetype-src")
set(bvh_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build/_deps/bvh-src")
set(lunasvg_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build/_deps/lunasvg-src")
set(stb_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build/_deps/stb-src")
set(miniaudio_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build/_deps/miniaudio-src")

# ffmpeg includes

install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavcodec" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavdevice" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavfilter" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavformat" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavutil" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libswresample" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libswscale" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
# datsit frrom ffmpeg


# angel headers

install(DIRECTORY ${ZG_SRC_INCLUDE}/angle DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/GL DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/glad DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/shaderc DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/SwiftShader DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/wayland DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${glm_SOURCE_DIR}/glm DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${freetype_SOURCE_DIR}/include/freetype DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(FILES ${freetype_SOURCE_DIR}/include/ft2build.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
install(DIRECTORY ${bvh_SOURCE_DIR}/src/bvh DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
    # lunasvg
install(FILES ${lunasvg_SOURCE_DIR}/include/lunasvg.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)

install(FILES ${stb_SOURCE_DIR}/stb_image.h ${stb_SOURCE_DIR}/stb_image_write.h ${stb_SOURCE_DIR}/stb_image_resize2.h
    ${stb_SOURCE_DIR}/stb_hexwave.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)

install(FILES ${miniaudio_SOURCE_DIR}/miniaudio.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)

install(DIRECTORY ${ZG_SRC_ABS}/include/zg DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)

install(FILES ../ZeungineConfig.cmake ../PlatformSetup.cmake ../Options.cmake DESTINATION ${ZG_SHR_INSTALL_PREFIX}
    PERMISSIONS WORLD_READ OWNER_READ GROUP_READ)
