set(ffmpeg_BINARY_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/ffmpeg-build")
set(glm_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/glm-src")
set(freetype_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/freetype-src")
set(bvh_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/bvh-src")
set(lunasvg_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/lunasvg-src")
set(stb_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/stb-src")
set(miniaudio_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/miniaudio-src")
set(openssl_INC_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-debug/_deps/openssl-build/include")
set(exprtk_SOURCE_DIR "${CMAKE_SOURCE_DIR}/../Dependencies/build-release/_deps/exprtk-src")

# openssl includes
if(NOT MACOS)
    install(DIRECTORY "${openssl_INC_DIR}/openssl" DESTINATION ${ZG_INC_INSTALL_PREFIX}
        FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
        DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
endif()

# ffmpeg includes

install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavcodec" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavdevice" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavfilter" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavformat" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavutil" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libswresample" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libswscale" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
# datsit frrom ffmpeg


# angel headers

install(DIRECTORY ${ZG_SRC_ABS}/include/angle DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY ${ZG_SRC_ABS}/include/GL DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY ${ZG_SRC_ABS}/include/glad DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY ${ZG_SRC_ABS}/include/shaderc DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY ${ZG_SRC_ABS}/include/SwiftShader DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY ${ZG_SRC_ABS}/include/wayland DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY ${glm_SOURCE_DIR}/glm DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(DIRECTORY ${freetype_SOURCE_DIR}/include/freetype DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)
install(FILES ${freetype_SOURCE_DIR}/include/ft2build.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT headers)
install(DIRECTORY ${bvh_SOURCE_DIR}/src/bvh DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)

install(FILES ${stb_SOURCE_DIR}/stb_image.h ${stb_SOURCE_DIR}/stb_image_write.h ${stb_SOURCE_DIR}/stb_image_resize2.h
    ${stb_SOURCE_DIR}/stb_hexwave.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT headers)

install(FILES ${miniaudio_SOURCE_DIR}/miniaudio.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT headers)

install(DIRECTORY ${ZG_SRC_ABS}/include/zg DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT headers)

install(FILES ${xprtk_SOURCE_DIR}/exprtk.hpp DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ GROUP_READ WORLD_READ
    COMPONENT headers)

set(CPACK_COMPONENT_HEADERS_DESCRIPTION "Zeungine Core & Dependency Headers")
set(CPACK_COMPONENT_HEADERS_GROUP "Zeungine")

install(FILES ../ZeungineConfig.cmake ../PlatformSetup.cmake ../Options.cmake ../Targets.cmake DESTINATION ${ZG_SHR_INSTALL_PREFIX}
    PERMISSIONS WORLD_READ OWNER_READ GROUP_READ
    COMPONENT cmakeconfig)

set(CPACK_COMPONENT_CMAKECONFIG_DESCRIPTION "Zeungine CMake Configuration")
set(CPACK_COMPONENT_CMAKECONFIG_GROUP "Zeungine")