
# ffmpeg includes

install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavcodec" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavdevice" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavfilter" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavformat" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavutil" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libswresample" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libswscale" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
# add when ZG_SHR_INSTALL_PREFIX becomes available vvvv.*
# install(DIRECTORY "${ffmpeg_BINARY_DIR}/share/ffmpeg" DESTINATION ${ZG_SHR_INSTALL_PREFIX}
#     FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
#     DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
if(WINDOWS)
    set(ffmpeg_LIB_PREFIX "lib")
    set(ffmpeg_LIB_SUFFIX "a")
    #  for a time:  only tested windows ffmpeg fully
elseif(MACOS)
    set(ffmpeg_LIB_PREFIX "lib")
    set(ffmpeg_LIB_SUFFIX "dylib")
else()
    set(ffmpeg_LIB_PREFIX "lib")
    set(ffmpeg_LIB_SUFFIX "so")
endif()
install(FILES
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avcodec.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avdevice.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avfilter.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avformat.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avutil.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}swresample.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}swscale.${ffmpeg_LIB_SUFFIX}"
    DESTINATION ${ZG_LIB_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
IF(MACOS OR LINUX)
    install(FILES
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avcodec.${ffmpeg_LIB_SUFFIX}.61"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avcodec.${ffmpeg_LIB_SUFFIX}.61.19.100"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avdevice.${ffmpeg_LIB_SUFFIX}.61"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avdevice.${ffmpeg_LIB_SUFFIX}.61.3.100"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avfilter.${ffmpeg_LIB_SUFFIX}.10"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avfilter.${ffmpeg_LIB_SUFFIX}.10.4.100"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avformat.${ffmpeg_LIB_SUFFIX}.61"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avformat.${ffmpeg_LIB_SUFFIX}.61.7.100"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avutil.${ffmpeg_LIB_SUFFIX}.59"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avutil.${ffmpeg_LIB_SUFFIX}.59.39.100"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}swresample.${ffmpeg_LIB_SUFFIX}.5"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}swresample.${ffmpeg_LIB_SUFFIX}.5.3.100"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}swscale.${ffmpeg_LIB_SUFFIX}.8"
        "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}swscale.${ffmpeg_LIB_SUFFIX}.8.3.100"
        DESTINATION ${ZG_LIB_INSTALL_PREFIX}
        PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
endif()
message(STATUS "ZG_LIB_INSTALL_PREFIX: ${ZG_LIB_INSTALL_PREFIX}")

# datsit frrom ffmpeg


# angel headers

install(DIRECTORY ${ZG_SRC_INCLUDE}/angle DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/GL DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/glad DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/shaderc DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/SwiftShader DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/wayland DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${glm_SOURCE_DIR}/glm DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${freetype_SOURCE_DIR}/include/freetype DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(FILES ${freetype_SOURCE_DIR}/include/ft2build.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
install(DIRECTORY ${bvh_SOURCE_DIR}/src/bvh DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
    # lunasvg
install(FILES ${lunasvg_SOURCE_DIR}/include/lunasvg.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
install(TARGETS freetype lunasvg glm shaderc_shared glslang SPIRV-Tools-shared
    ARCHIVE DESTINATION ${ZG_LIB_INSTALL_PREFIX}
    LIBRARY DESTINATION ${ZG_LIB_INSTALL_PREFIX})

install(FILES ${stb_SOURCE_DIR}/stb_image.h ${stb_SOURCE_DIR}/stb_image_write.h ${stb_SOURCE_DIR}/stb_image_resize2.h
    ${stb_SOURCE_DIR}/stb_hexwave.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)

# if linux whoami
if(LINUX)
    execute_process(COMMAND whoami
        OUTPUT_VARIABLE CURRENT_USER
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(INC_CHOWN_COMMAND "sudo chown -R ${CURRENT_USER}:${CURRENT_USER} ${ZG_INC_INSTALL_PREFIX}")
    install(CODE "
    execute_process(COMMAND ${INC_CHOWN_COMMAND})
")
endif()
#    |"':{|<["iflinuxwhoami"]>|}.'"|  ??

if(LINUX)
    install(CODE "execute_process(COMMAND /bin/sh -c \"echo ${ZG_LIB_INSTALL_PREFIX} > ${LD_CONF_FILE}\")")
    install(CODE "execute_process(COMMAND /bin/sh -c \"ldconfig\")")
endif()