
# ffmpeg includes

install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavcodec" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavdevice" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavfilter" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavformat" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libavutil" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libswresample" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY "${ffmpeg_BINARY_DIR}/include/libswscale" DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
# add when ZG_SHR_INSTALL_PREFIX becomes available vvvv.*
# install(DIRECTORY "${ffmpeg_BINARY_DIR}/share/ffmpeg" DESTINATION ${ZG_SHR_INSTALL_PREFIX}
#     FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
#     DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
if(WINDOWS)
    set(ffmpeg_LIB_PREFIX "lib")
    set(ffmpeg_LIB_SUFFIX "a")
    #  for a time:  only tested windows ffmpeg fully
elseif(MACOS)
    set(ffmpeg_LIB_PREFIX "lib")
    set(ffmpeg_LIB_SUFFIX "a")
else()
    set(ffmpeg_LIB_PREFIX "lib")
    set(ffmpeg_LIB_SUFFIX "a")
endif()
install(FILES
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avcodec.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avdevice.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avfilter.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avformat.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}avutil.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}swresample.${ffmpeg_LIB_SUFFIX}"
    "${ffmpeg_BINARY_DIR}/lib/${ffmpeg_LIB_PREFIX}swscale.${ffmpeg_LIB_SUFFIX}"
    DESTINATION ${ZG_LIB_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)

# datsit frrom ffmpeg


# angel headers

install(DIRECTORY ${ZG_SRC_INCLUDE}/angle DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/GL DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/glad DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/shaderc DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/SwiftShader DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${ZG_SRC_INCLUDE}/wayland DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${glm_SOURCE_DIR}/glm DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(DIRECTORY ${freetype_SOURCE_DIR}/include/freetype DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
install(FILES ${freetype_SOURCE_DIR}/include/ft2build.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
install(FILES ${freetype_BINARY_DIR}/Debug/freetype.lib ${freetype_BINARY_DIR}/Debug/freetype.pdb
    DESTINATION ${ZG_LIB_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
install(DIRECTORY ${bvh_SOURCE_DIR}/src/bvh DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)
# lunasvg
install(FILES ${lunasvg_BINARY_DIR}/Debug/lunasvg.lib ${lunasvg_BINARY_DIR}/Debug/lunasvg.pdb
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
install(FILES ${lunasvg_SOURCE_DIR}/include/lunasvg.h
    DESTINATION ${ZG_INC_INSTALL_PREFIX}
    PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)


# if linux whoami
if(LINUX)
    execute_process(COMMAND whoami
        OUTPUT_VARIABLE CURRENT_USER
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    set(INC_CHOWN_COMMAND "sudo chown -R ${CURRENT_USER}:${CURRENT_USER} ${ZG_INC_INSTALL_PREFIX}")
    install(CODE "
    execute_process(COMMAND ${INC_CHOWN_COMMAND})
")
endif()
#    |"':{|<["iflinuxwhoami"]>|}.'"|  ??