#include <zg/Entity.hpp>
#include <zg/Scene.hpp>
#include <zg/components/entities/RigidBody.hpp>
#include <zg/components/scenes/PhysicsScene.hpp>
using namespace zg::components::entities;
RigidBody::RigidBody(const RigidBodyInfo& info) :
		IEntityComponent("RigidBody"), info(info), transform(&info.entity.getModelMatrix()),
		position(&info.entity.position), rotation(&info.entity.rotation)
{
}
void RigidBody::addCollider(Collider* collider) { colliders.push_back(collider); }
void RigidBody::removeCollider(Collider* collider)
{
	for (auto iter = colliders.begin(), end = colliders.end(); iter != end; iter++)
	{
		if (*iter == collider)
		{
			colliders.erase(iter);
			break;
		}
	}
}
void RigidBody::onAttached()
{
	physicsScene = dynamic_cast<scenes::PhysicsScene*>(info.entity.scene.getComponentByName("PhysicsScene").get());
	if (!physicsScene)
	{
		throw std::runtime_error("RigidBody component must not be added to an entity before the scene the entity is in has "
														 "an attached PhysicsScene component");
	}
	inverseMass = 1.f / info.mass;
	if (info.bodyType == BodyType::Dynamic && info.mass > 0.0f)
	{
		inverseMass = 1.0f / info.mass;
	}
	else
	{
		inverseMass = 0.0f; // Static or Kinematic bodies have infinite mass
		linearVelocity = {0, 0, 0}; // Ensure non-dynamic bodies start stationary
		angularVelocity = {0, 0, 0};
	}

	// TODO: Calculate inverse inertia tensor based on mass and collider shapes/offsets

	physicsScene->registerRigidBody(this);

	std::cout << "RigidBody attached." << std::endl;
}
void RigidBody::onUpdate()
{
	// This is the engine's per-frame update, not the fixed physics step.
	// Could be used for:
	// - Applying continuous user forces (though often better just before physics update)
	// - Updating kinematic target positions/rotations before the physics step reads them.
}
void RigidBody::onDetached()
{
	// Unregister from the physics system
	if (physicsScene)
	{
		physicsScene->unregisterRigidBody(this);
	}
	physicsScene = nullptr;
	transform = nullptr; // Clear pointer
	std::cout << "RigidBody detached." << std::endl;
}
void RigidBody::applyForce(glm::vec3 force, glm::vec3 worldPoint)
{
	if (!isDynamic())
		return; // Only dynamic bodies respond to forces

	// Apply linear force
	forceAccumulator += force;

	// Apply torque generated by the force applied at an offset
	if (transform)
	{
		glm::vec3 centerOfMass = glm::vec3((*transform)[3]); // Position is column 3
		glm::vec3 pointRelative = worldPoint - centerOfMass;
		torqueAccumulator += glm::cross(pointRelative, force);
	}
}
void RigidBody::applyForceToCenter(glm::vec3 force)
{
	if (!isDynamic())
		return;
	forceAccumulator += force;
	// No torque generated when applied to the center of mass
}
void RigidBody::applyTorque(glm::vec3 torque)
{
	if (!isDynamic())
		return;
	torqueAccumulator += torque;
}
void RigidBody::clearForces()
{
	forceAccumulator = glm::vec3(0);
	torqueAccumulator = glm::vec3(0);
}

glm::vec3 RigidBody::getPosition() const
{
	if (!position)
		return glm::vec3(0);
	return *position;
}

glm::vec3 RigidBody::getRotation() const
{
	if (!rotation)
		return glm::vec3(0);
	return *rotation;
}

glm::quat RigidBody::getOrientation() const
{
	return orientation;
}

void RigidBody::setPosition(glm::vec3 pos)
{
	if (!position)
		return;
	*position = pos;
}

void RigidBody::setRotation(glm::vec3 rot)
{
	if (!rotation)
		return;
	*rotation += rot;
}

void RigidBody::translate(glm::vec3 deltaPos)
{
	if (!position)
		return;
	// More efficient than setPosition(getPosition() + deltaPos)
	*position += deltaPos;
}
bool RigidBody::isStatic() const { return info.bodyType == BodyType::Static; }
bool RigidBody::isKinematic() const { return info.bodyType == BodyType::Kinematic; }
bool RigidBody::isDynamic() const { return info.bodyType == BodyType::Dynamic; }
glm::mat3 RigidBody::getInverseInertiaTensorWorld() const
{
	// Static objects have infinite inertia -> zero inverse inertia
	if (isStatic())
	{
		return glm::mat3(0.0f);
	}

	// 1. Convert the orientation quaternion to a 3x3 rotation matrix (R)
	// This matrix transforms vectors from body-space to world-space.
	glm::mat3 R = glm::toMat3(orientation);

	// 2. Get the body-space inverse inertia tensor (I_body_inv)
	const glm::mat3& I_body_inv = this->inverseInertiaTensor;

	// 3. Calculate I_world_inv = R * I_body_inv * R^T
	//    (where R^T is the transpose of R)
	// Note: Matrix multiplication order matters!
	glm::mat3 I_world_inv = R * I_body_inv * glm::transpose(R);

	// 4. Return the result
	return I_world_inv;
}
