
install(TARGETS zeungine
    ARCHIVE DESTINATION ${ZG_LIB_INSTALL_PREFIX}
    LIBRARY DESTINATION ${ZG_LIB_INSTALL_PREFIX}
    COMPONENT core)
set(CPACK_COMPONENT_CORE_DESCRIPTION "Zeungine Core Library")
set(CPACK_COMPONENT_CORE_GROUP "Zeungine")

install(TARGETS zedit DESTINATION ${ZG_BIN_INSTALL_PREFIX} COMPONENT zedit)
set(CPACK_COMPONENT_ZEDIT_DESCRIPTION "Zeungine Editor [zedit]")
set(CPACK_COMPONENT_ZEDIT_GROUP "Zeungine")
if((LINUX OR MACOS) AND "${CMAKE_BUILD_TYPE}" MATCHES "Release")
    get_filename_component(ZG_BIN_INSTALL_PREFIX_UP2 "${ZG_BIN_INSTALL_PREFIX}/../.." ABSOLUTE)
    install(CODE "execute_process(COMMAND rm ${ZG_BIN_INSTALL_PREFIX_UP2}/zedit)")
    install(CODE "execute_process(COMMAND ln -s ${ZG_BIN_INSTALL_PREFIX}/zedit ${ZG_BIN_INSTALL_PREFIX_UP2}/zedit)")
endif()

if(WINDOWS)
    set(PATH_TO_ADD "C:\\\\Program Files\\\\Zeungine\\\\${CMAKE_BUILD_TYPE}")
    install(CODE "
        execute_process(
            COMMAND powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"
                \$dirToAdd='${PATH_TO_ADD}';
                \$envPath=[System.Environment]::GetEnvironmentVariable('Path', [System.EnvironmentVariableTarget]::User);
                if (-not \$envPath -or \$envPath.Split(';') -notcontains \$dirToAdd) {
                    \$newPath = (\$envPath + ';' + \$dirToAdd).Trim(';');
                    [System.Environment]::SetEnvironmentVariable('Path', \$newPath, [System.EnvironmentVariableTarget]::User);
                }
            \"
        )
    ")
endif()

install(DIRECTORY fonts DESTINATION ${ZG_BIN_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT assets)
install(DIRECTORY icons DESTINATION ${ZG_BIN_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT assets)
install(DIRECTORY images DESTINATION ${ZG_BIN_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT assets)
install(DIRECTORY music DESTINATION ${ZG_BIN_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT assets)
install(DIRECTORY videos DESTINATION ${ZG_BIN_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ
    COMPONENT assets)
set(CPACK_COMPONENT_ASSETS_DESCRIPTION "Zeungine Core Assets")
set(CPACK_COMPONENT_ASSETS_GROUP "Zeungine")