install(DIRECTORY include/zg DESTINATION ${ZG_INC_INSTALL_PREFIX}
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    DIRECTORY_PERMISSIONS OWNER_EXECUTE OWNER_READ OWNER_WRITE GROUP_EXECUTE GROUP_READ WORLD_EXECUTE WORLD_READ)

install(TARGETS zeungine
    ARCHIVE DESTINATION ${ZG_LIB_INSTALL_PREFIX}
    LIBRARY DESTINATION ${ZG_LIB_INSTALL_PREFIX})