# Add Zeungine library
add_library(zeungine ${ZG_LIBRARY_TYPE} ${ZG_SOURCES})
# target_include_directories(zeungine PRIVATE ${Vulkan_INCLUDE_DIRS})
# target_include_directories(zeungine PRIVATE ${protobuf_SOURCE_DIR}/src)
# target_include_directories(zeungine PRIVATE ${absl_SOURCE_DIR})
target_include_directories(zeungine PRIVATE include)
target_include_directories(zeungine PRIVATE include/angle)
target_include_directories(zeungine PRIVATE include/SwiftShader)
target_include_directories(zeungine PRIVATE ${ZG_INC_INSTALL_PREFIX_ABS})
target_compile_definitions(zeungine PRIVATE TRACY_ENABLE)
if(MACOS)
    target_include_directories(zeungine PRIVATE ${OPENSSL_INCLUDE_DIR})
endif()
insert_library_before(glsl zeungine ZG_LIBRARIES)
# set(ZG_LIBRARIES zeungine ${ZG_LIBRARIES})
message(STATUS "ZG_LIBRARIES: ${ZG_LIBRARIES}")