# Options
#  these objects work because their source is pure absolute just include readpath from build include
option(BUILD_GL             "Whether to build OpenGL module" OFF)
option(BUILD_EGL            "Whether to build EGL module" OFF)
option(BUILD_VULKAN         "Whether to build Vulkan module" ON)
option(BUILD_EDITOR         "Whether to build the Zeungine editor" ON)
option(ZG_INSTALL           "Whether to install Zeungine" ON)
option(ZG_INSTALL_TESTS     "Whether to install Zeungine tests" ON)
option(ZG_PACKAGE           "Whether to package Zeungine" OFF)
set   (ZG_SRC_ABS           ${CMAKE_CURRENT_LIST_DIR}/..) # valid in, in source configures only
get_filename_component(ZG_SRC_ABS "${ZG_SRC_ABS}" ABSOLUTE)
if(ZG_INSTALL)
    include(GNUInstallDirs)
    if(LINUX OR MACOS)
        set(ZG_UNX_INSTALL_PREFIX /usr/local)
        set(ZG_SRC_INSTALL_PREFIX ${ZG_UNX_INSTALL_PREFIX}/src/zg)
        set(ZG_LIB_INSTALL_PREFIX ${ZG_UNX_INSTALL_PREFIX}/lib/zg/${CMAKE_BUILD_TYPE})
        set(ZG_LIB_INSTALL_PREFIX_ABS ${ZG_UNX_INSTALL_PREFIX}/lib/zg/${CMAKE_BUILD_TYPE})
        set(ZG_INC_INSTALL_PREFIX ${ZG_UNX_INSTALL_PREFIX}/include/zg)
        set(ZG_INC_INSTALL_PREFIX_ABS ${ZG_INC_INSTALL_PREFIX})
        set(ZG_AST_INSTALL_PREFIX ${ZG_SRC_INSTALL_PREFIX}/assets)
        set(ZG_SHR_INSTALL_PREFIX /usr/share/cmake/Zeungine)
        set(ZG_BIN_INSTALL_PREFIX ${ZG_UNX_INSTALL_PREFIX}/bin/zg/${CMAKE_BUILD_TYPE})
    elseif(WINDOWS)
        set(ZG_WIN_INSTALL_PREFIX "C:/Program Files/Zeungine")
        set(ZG_SRC_INSTALL_PREFIX "src")
        set(ZG_LIB_INSTALL_PREFIX "${CMAKE_BUILD_TYPE}")
        set(ZG_LIB_INSTALL_PREFIX_ABS "${ZG_WIN_INSTALL_PREFIX}/${ZG_LIB_INSTALL_PREFIX}")
        set(ZG_INC_INSTALL_PREFIX "include")
        set(ZG_INC_INSTALL_PREFIX_ABS "${ZG_WIN_INSTALL_PREFIX}/${ZG_INC_INSTALL_PREFIX}")
        set(ZG_AST_INSTALL_PREFIX "assets")
        set(ZG_SHR_INSTALL_PREFIX "share/Zeungine/cmake")
        set(ZG_BIN_INSTALL_PREFIX "${ZG_LIB_INSTALL_PREFIX}")
    endif()
    add_definitions(-DZG_SRC_INSTALL_PREFIX="${ZG_SRC_INSTALL_PREFIX}")
    add_definitions(-DZG_LIB_INSTALL_PREFIX="${ZG_LIB_INSTALL_PREFIX_ABS}")
    add_definitions(-DZG_INC_INSTALL_PREFIX="${ZG_INC_INSTALL_PREFIX_ABS}")
    add_definitions(-DZG_AST_INSTALL_PREFIX="${ZG_AST_INSTALL_PREFIX}")
    add_definitions(-DZG_SHR_INSTALL_PREFIX="${ZG_SHR_INSTALL_PREFIX}")
    set(CMAKE_INSTALL_LIBDIR ${ZG_LIB_INSTALL_PREFIX})
    set(CMAKE_INSTALL_BINDIR ${ZG_LIB_INSTALL_PREFIX}) 
    message(STATUS "ZG_LIB_INSTALL_PREFIX: ${ZG_LIB_INSTALL_PREFIX}")
endif()
set(ZG_LIBRARIES "")