message(STATUS "Build type is ${CMAKE_BUILD_TYPE}")

# Determine platform and set defines
if("${CMAKE_SYSTEM_NAME}" MATCHES "Linux")
    set(LINUX ON)
    set(ZG_LIB_PREFIX "lib")
    set(SHARED_ZG_LIB_SUFFIX ".so")
    set(STATIC_ZG_LIB_SUFFIX ".a")
    if(ZG_INSTALL)
        file(READ "/etc/os-release" OS_RELEASE)
        string(REGEX MATCH "Debian|Ubuntu|Fedora" DIST ${OS_RELEASE})
        if(DIST STREQUAL "Debian" OR
            DIST STREQUAL "Ubuntu")
            set(DEB true)
        elseif(DIST STREQUAL "Fedora")
            set(RPM true)
        else()
            message(FATAL_ERROR ">>>> Found unknown distribution <<<<")
        endif()
    endif()
elseif("${CMAKE_SYSTEM_NAME}" MATCHES "Darwin")
    set(MACOS ON)
    add_definitions(-DMACOS)
    set(ZG_LIB_PREFIX "lib")
    set(SHARED_ZG_LIB_SUFFIX ".dylib")
    set(STATIC_ZG_LIB_SUFFIX ".a")
elseif(WIN32)
    set(WINDOWS ON)
    set(ZG_LIB_PREFIX "")
    set(SHARED_ZG_LIB_SUFFIX ".dll")
    set(STATIC_ZG_LIB_SUFFIX ".lib")
endif()

# Set library directory
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug)
endif()
if(("${CMAKE_BUILD_TYPE}" MATCHES "Release") OR ("${CMAKE_BUILD_TYPE}" MATCHES "MinSizeRel"))
    set(RELEASE_OR_DEBUG "Release")
    set(BUILD_POSTFIX "")
    if(WINDOWS)
        set(C_RUNTIME "MT")
    endif()
elseif(("${CMAKE_BUILD_TYPE}" MATCHES "Debug") OR ("${CMAKE_BUILD_TYPE}" MATCHES "RelWithDebInfo"))
    set(RELEASE_OR_DEBUG "Debug")
    set(BUILD_POSTFIX "-debug")
    if(WINDOWS)
        set(C_RUNTIME "MTd")
    endif()
endif()

if(ZG_TYPE STREQUAL STATIC)
    set(BUILD_POSTFIX ${BUILD_POSTFIX}-static)
endif()

# Add build flags
if(LINUX OR MACOS)
    if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g")
    endif()
	set(LD_CONF_FILE "/etc/ld.so.conf.d/zg${CMAKE_BUILD_TYPE}.conf")
elseif(WINDOWS)
#     set(CMAKE_CXX_FLAGS "/${C_RUNTIME} ${CMAKE_CXX_FLAGS} /wd4068")
endif()

if(LINUX OR MACOS)
    set(BUILD_SHARED_LIBS OFF)
else()
endif()

# setup target helper
function(zg_setup_target
	TARGET_NAME
	LIBRARY_TYPE
	LIBRARY_DIR
	LIBRARY_PREFIX LIBRARY_NAME IMPLIB_NAME LIBRARY_SUFFIX
    ADD_TO_ZG_LIBRARIES)
	add_library(${TARGET_NAME} ${LIBRARY_TYPE} IMPORTED)
	if(WIN32)
		if(${LIBRARY_TYPE} STREQUAL "STATIC")
			set(LIBRARY_LOCATION "${LIBRARY_DIR}/${LIBRARY_PREFIX}${LIBRARY_NAME}${LIBRARY_SUFFIX}")
		elseif(${LIBRARY_TYPE} STREQUAL "SHARED")
			set(LIBRARY_LOCATION "${LIBRARY_DIR}/${LIBRARY_NAME}.dll")
			set(IMPLIB_LOCATION "${LIBRARY_DIR}/${IMPLIB_NAME}.lib")
			set_target_properties(${TARGET_NAME} PROPERTIES IMPORTED_IMPLIB ${IMPLIB_LOCATION})
		endif()
	else()
		set(LIBRARY_LOCATION "${LIBRARY_DIR}/${LIBRARY_PREFIX}${LIBRARY_NAME}${LIBRARY_SUFFIX}")
	endif()
    set(LAST_LIBRARY_LOCATION ${LIBRARY_LOCATION} PARENT_SCOPE)
    set(LAST_TARGET_NAME ${TARGET_NAME} PARENT_SCOPE)
    if(ADD_TO_ZG_LIBRARIES)
        set(ZG_LIBRARIES ${ZG_LIBRARIES} ${TARGET_NAME} PARENT_SCOPE)
    endif()
    if(EXISTS "${LIBRARY_LOCATION}")
        set(LIBRARY_EXISTS "exists")
    else()
        set(LIBRARY_EXISTS "does not exist")
    endif()
	set_target_properties(${TARGET_NAME} PROPERTIES IMPORTED_LOCATION ${LIBRARY_LOCATION})
endfunction()

function(insert_library_before TARGET LIBRARY_LIST VAR)
    list(FIND ${VAR} ${TARGET} TARGET_INDEX)
    if(NOT TARGET_INDEX EQUAL -1)
        list(INSERT ${VAR} ${TARGET_INDEX} ${LIBRARY_LIST})
        set(${VAR} ${${VAR}} PARENT_SCOPE)
    endif()
endfunction()

function(insert_library_after TARGET LIBRARY_LIST VAR)
    list(FIND ${VAR} ${TARGET} TARGET_INDEX)
    if(NOT TARGET_INDEX EQUAL -1)
        math(EXPR TARGET_INDEX "${TARGET_INDEX} + 1")
        list(INSERT ${VAR} ${TARGET_INDEX} ${LIBRARY_LIST})
        set(${VAR} ${${VAR}} PARENT_SCOPE)
    endif()
endfunction()

# Library type, Static if Windows, otherwise Shared
set(ZG_LIBRARY_TYPE STATIC)
# if(WIN32)
# else()
#     set(ZG_LIBRARY_TYPE SHARED)
# endif()
if(ZG_TYPE STREQUAL STATIC)
    set(BUILD_SHARED_LIBS OFF)
elseif(ZG_TYPE STREQUAL SHARED)
    set(BUILD_SHARED_LIBS ON)
else()
    message(FATAL_ERROR "Unsupported ZG_TYPE: ${ZG_TYPE}")
endif()

if(ZG_INSTALL)
    include(GNUInstallDirs)
    if(LINUX OR MACOS)
        set(ZG_UNX_INSTALL_PREFIX /usr/local)
        set(ZG_SRC_INSTALL_PREFIX ${ZG_UNX_INSTALL_PREFIX}/src/zg)
        set(ZG_LIB_INSTALL_PREFIX ${ZG_UNX_INSTALL_PREFIX}/lib/zg/${CMAKE_BUILD_TYPE}/${ZG_TYPE})
        set(ZG_LIB_INSTALL_PREFIX_ABS ${ZG_UNX_INSTALL_PREFIX}/lib/zg/${CMAKE_BUILD_TYPE}/${ZG_TYPE})
        set(ZG_INC_INSTALL_PREFIX ${ZG_UNX_INSTALL_PREFIX}/include/zg)
        set(ZG_INC_INSTALL_PREFIX_ABS ${ZG_INC_INSTALL_PREFIX})
        set(ZG_AST_INSTALL_PREFIX ${ZG_SRC_INSTALL_PREFIX}/assets)
        set(ZG_SHR_INSTALL_PREFIX /usr/share/cmake/Zeungine)
        set(ZG_BIN_INSTALL_PREFIX ${ZG_UNX_INSTALL_PREFIX}/bin/zg/${CMAKE_BUILD_TYPE}/${ZG_TYPE})
    elseif(WINDOWS)
        set(ZG_WIN_INSTALL_PREFIX "C:/Program Files/Zeungine")
        set(ZG_SRC_INSTALL_PREFIX "src")
        set(ZG_LIB_INSTALL_PREFIX "${CMAKE_BUILD_TYPE}/${ZG_TYPE}")
        set(ZG_LIB_INSTALL_PREFIX_ABS "${ZG_WIN_INSTALL_PREFIX}/${ZG_LIB_INSTALL_PREFIX}")
        set(ZG_INC_INSTALL_PREFIX "include")
        set(ZG_INC_INSTALL_PREFIX_ABS "${ZG_WIN_INSTALL_PREFIX}/${ZG_INC_INSTALL_PREFIX}")
        set(ZG_AST_INSTALL_PREFIX "assets")
        set(ZG_SHR_INSTALL_PREFIX "share/Zeungine/cmake")
        set(ZG_BIN_INSTALL_PREFIX "${ZG_LIB_INSTALL_PREFIX}")
    endif()
    add_definitions(-DZG_SRC_INSTALL_PREFIX="${ZG_SRC_INSTALL_PREFIX}")
    add_definitions(-DZG_LIB_INSTALL_PREFIX="${ZG_LIB_INSTALL_PREFIX_ABS}")
    add_definitions(-DZG_INC_INSTALL_PREFIX="${ZG_INC_INSTALL_PREFIX_ABS}")
    add_definitions(-DZG_AST_INSTALL_PREFIX="${ZG_AST_INSTALL_PREFIX}")
    add_definitions(-DZG_SHR_INSTALL_PREFIX="${ZG_SHR_INSTALL_PREFIX}")
    set(CMAKE_INSTALL_LIBDIR ${ZG_LIB_INSTALL_PREFIX})
    set(CMAKE_INSTALL_BINDIR ${ZG_LIB_INSTALL_PREFIX}) 
    message(STATUS "ZG_LIB_INSTALL_PREFIX: ${ZG_LIB_INSTALL_PREFIX}")
endif()
set(ZG_LIBRARIES "")

if(WIN32)
    if(ZG_TYPE STREQUAL SHARED)
        set(ffmpeg_ZG_LIB_PREFIX "")
        set(ffmpeg_ZG_LIB_SUFFIX "dll")
    elseif(ZG_TYPE STREQUAL STATIC)
        set(ffmpeg_ZG_LIB_PREFIX "lib")
        set(ffmpeg_ZG_LIB_SUFFIX "a")
    endif()
elseif(APPLE)
    set(ffmpeg_ZG_LIB_PREFIX "lib")
    if(ZG_TYPE STREQUAL SHARED)
        set(ffmpeg_ZG_LIB_SUFFIX "dylib")
    elseif(ZG_TYPE STREQUAL STATIC)
        set(ffmpeg_ZG_LIB_SUFFIX "a")
    endif()
else()
    set(ffmpeg_ZG_LIB_PREFIX "lib")
    if(ZG_TYPE STREQUAL SHARED)
        set(ffmpeg_ZG_LIB_SUFFIX "so")
    elseif(ZG_TYPE STREQUAL STATIC)
        set(ffmpeg_ZG_LIB_SUFFIX "a")
    endif()
endif()