message(STATUS "Build type is ${CMAKE_BUILD_TYPE}")

# Determine platform and set defines
if("${CMAKE_SYSTEM_NAME}" MATCHES "Linux")
    set(LINUX ON)
    set(LIB_PREFIX "lib")
    set(SHARED_LIB_SUFFIX ".so")
    set(STATIC_LIB_SUFFIX ".a")
    if(ZG_INSTALL)
        file(READ "/etc/os-release" OS_RELEASE)
        string(REGEX MATCH "Debian|Ubuntu|Fedora" DIST ${OS_RELEASE})
        if(DIST STREQUAL "Debian" OR
            DIST STREQUAL "Ubuntu")
            set(DEB true)
        elseif(DIST STREQUAL "Fedora")
            set(RPM true)
        else()
            message(FATAL_ERROR ">>>> Found unknown distribution <<<<")
        endif()
    endif()
elseif("${CMAKE_SYSTEM_NAME}" MATCHES "Darwin")
    set(MACOS ON)
    set(LIB_PREFIX "lib")
    set(SHARED_LIB_SUFFIX ".dylib")
    set(STATIC_LIB_SUFFIX ".a")
elseif(WIN32)
    set(WINDOWS ON)
    set(LIB_PREFIX "")
    set(SHARED_LIB_SUFFIX ".dll")
    set(STATIC_LIB_SUFFIX ".lib")
endif()

# Set library directory
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug)
endif()
if(("${CMAKE_BUILD_TYPE}" MATCHES "Release") OR ("${CMAKE_BUILD_TYPE}" MATCHES "MinSizeRel"))
    set(RELEASE_OR_DEBUG "Release")
    set(BUILD_POSTFIX "")
    if(WINDOWS)
        set(C_RUNTIME "MT")
    endif()
elseif(("${CMAKE_BUILD_TYPE}" MATCHES "Debug") OR ("${CMAKE_BUILD_TYPE}" MATCHES "RelWithDebInfo"))
    set(RELEASE_OR_DEBUG "Debug")
    set(BUILD_POSTFIX "-debug")
    if(WINDOWS)
        set(C_RUNTIME "MTd")
    endif()
endif()
set(ZG_LIB_DIR "${CMAKE_SOURCE_DIR}/lib/${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_PROCESSOR}/${RELEASE_OR_DEBUG}")
message(STATUS "ZG_LIB_DIR: ${ZG_LIB_DIR}")

# Add build flags
if(LINUX OR MACOS)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -w -fPIC")
    if("${CMAKE_BUILD_TYPE}" STREQUAL "Debug")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g")
    endif()
	set(LD_CONF_FILE "/etc/ld.so.conf.d/zg${CMAKE_BUILD_TYPE}.conf")
elseif(WINDOWS)
#     set(CMAKE_CXX_FLAGS "/${C_RUNTIME} ${CMAKE_CXX_FLAGS} /wd4068")
endif()

if(LINUX OR MACOS)
    set(BUILD_SHARED_LIBS OFF)
else()
    set(BUILD_SHARED_LIBS ON)
endif()