include(CTest)
enable_testing()
# create_test function
function(create_test TEST_NAME TEST_SOURCE TEST_ARGS LIBRARY)
    if(LIBRARY)
        add_library(${TEST_NAME} SHARED ${TEST_SOURCE})
    else()
        add_executable(${TEST_NAME} ${TEST_SOURCE})
    endif()
    target_link_libraries(${TEST_NAME} ${ZG_LIBRARIES})
    target_include_directories(${TEST_NAME} PRIVATE include)
    target_include_directories(${TEST_NAME} PRIVATE ${ZG_INC_INSTALL_PREFIX_ABS})
    if(NOT LIBRARY)
        add_test(NAME ${TEST_NAME} COMMAND $<TARGET_FILE_DIR:${TEST_NAME}>/${TEST_NAME}${TEST_EXT} ${TEST_ARGS})
    endif()
    if(WINDOWS)
        set(TEST_SUFFIX ".exe")
    endif()
    if(ZG_INSTALL_TESTS)
        install(FILES ${CMAKE_BINARY_DIR}/${TEST_NAME}${TEST_SUFFIX}
            DESTINATION ${ZG_BIN_INSTALL_PREFIX}
            PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
            COMPONENT tests)
    endif()
endfunction()

# Tests
create_test(LightingTest tests/LightingTest.cpp "" FALSE)
create_test(SimpleCubeTest tests/SimpleCubeTest.cpp "" FALSE)
create_test(VideoTest tests/VideoTest.cpp "" FALSE)
create_test(SimpleWindowTest tests/SimpleWindowTest.cpp "" FALSE)
create_test(queueTest tests/queueTest.cpp "" FALSE)
create_test(dequeTest tests/dequeTest.cpp "" FALSE)
create_test(SerialTest tests/SerialTest.cpp "" FALSE)
create_test(MERTest tests/MERTest.cpp "" FALSE)
create_test(http_clientTest tests/http_clientTest.cpp "" FALSE)
create_test(p2pTest tests/p2pTest.cpp "" FALSE)
create_test(mcTest tests/mcTest.cpp "" FALSE)
create_test(CurveTest tests/CurveTest.cpp "" FALSE)
create_test(multiindexTest tests/multiindexTest.cpp "" FALSE)
create_test(PhysicsTest tests/PhysicsTest.cpp "" FALSE)
create_test(Pair_1_2_2_1_Test tests/Pair_1_2_2_1_Test.cpp "" FALSE)
create_test(TOITest tests/TOITest.cpp "" FALSE)