name: Build Test and Package
on:
  push:
    tags:
      - '**'
      - '!v*.*.*.*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt install nasm libvulkan-dev libx11-dev uuid-dev libglx-dev libgl1-mesa-dev libxfixes-dev libxrandr-dev libxkbcommon-dev libxcb-keysyms1-dev libdrm-dev ninja-build libwayland-client0 libwayland-server0 libwayland-dev libxfixes-dev libxcb-xfixes0-dev libxrender-dev libxrandr-dev libxcb-util-dev libdrm-dev
        shell: bash

      - name: Install Dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install dos2unix ninja nasm
          C:\\msys64\\msys2_shell.cmd -defterm -no-start -mingw64 -here -use-full-path -c "pacman -S --noconfirm make diffutils"
        shell: bash

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: Build Package on Linux
        if: runner.os == 'Linux'
        run: ./unx-package.sh 0
        shell: bash

      - name: Build Package on Windows
        if: runner.os == 'Windows'
        run: .\win-package.bat 0
        shell: cmd