name: Release on Tag
on:
  push:
    tags:
      - 'v*.*.*.*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt install nasm libx11-dev uuid-dev libglx-dev libgl1-mesa-dev libxfixes-dev libxrandr-dev libxkbcommon-dev libdrm-dev ninja-build
        shell: bash

      - name: Install Dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install dos2unix
          C:\\msys64\\msys2_shell.cmd -defterm -no-start -mingw64 -here -use-full-path -c "pacman -S --noconfirm make diffutils"
        shell: bash

      # - name: Build Package on Linux
      #   if: runner.os == 'Linux'
      #   run: ./unx-package.sh 0
      #   shell: bash

      # - name: Build Package on Windows
      #   if: runner.os == 'Windows'
      #   run: .\win-package.bat 8
      #   shell: cmd

      - name: Compile Release Notes
        if: runner.os == 'Linux'
        id: notes
        run: |
          PREV_HASH=$(git for-each-ref --sort=-creatordate --format '%(objectname)' refs/tags | sed -n 2p)
          CURR_HASH=$(git rev-parse HEAD)
          export CHANGELOG="$(git log $PREV_HASH..$CURR_HASH --oneline)"
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$CHANGELOG"
        shell: bash
      
      - name: Create Release
        if: runner.os == 'Linux'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            changes since the previous tag included in this release:
            ${{ steps.notes.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Linux Upload
      # - name: Upload releases/zeungine.deb
      #   if: runner.os == 'Linux'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.create_release.outputs.upload_url}}
      #     asset_path: ./releases/zeungine.deb
      #     asset_name: zeungine.deb
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/zeungine-debug.deb
      #   if: runner.os == 'Linux'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.create_release.outputs.upload_url}}
      #     asset_path: ./releases/zeungine-debug.deb
      #     asset_name: zeungine-debug.deb
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/zeungine-debug-static.deb
      #   if: runner.os == 'Linux'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.create_release.outputs.upload_url}}
      #     asset_path: ./releases/zeungine-debug-static.deb
      #     asset_name: zeungine-debug-static.deb
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/zeungine-dependencies.deb
      #   if: runner.os == 'Linux'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.create_release.outputs.upload_url}}
      #     asset_path: ./releases/zeungine-dependencies.deb
      #     asset_name: zeungine-dependencies.deb
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/zeungine-dependencies-debug.deb
      #   if: runner.os == 'Linux'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.create_release.outputs.upload_url}}
      #     asset_path: ./releases/zeungine-dependencies-debug.deb
      #     asset_name: zeungine-dependencies-debug.deb
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/zeungine-dependencies-debug-static.deb
      #   if: runner.os == 'Linux'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.create_release.outputs.upload_url}}
      #     asset_path: ./releases/zeungine-dependencies-debug-static.deb
      #     asset_name: zeungine-dependencies-debug-static.deb
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/zeungine-headers.deb
      #   if: runner.os == 'Linux'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.create_release.outputs.upload_url}}
      #     asset_path: ./releases/zeungine-headers.deb
      #     asset_name: zeungine-headers.deb
      #     asset_content_type: application/octet-stream
      - name: Upload deb-auto-install.sh
        if: runner.os == 'Linux'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{steps.create_release.outputs.upload_url}}
          asset_path: ./deb-auto-install.sh
          asset_name: deb-auto-install.sh
          asset_content_type: application/octet-stream
      
      # Windows upload
      - name: Get uploadUrl for Windows
        if: runner.os == 'Windows'
        id: get_upload_url_windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $ErrorActionPreference = "Stop"
          $release = Invoke-RestMethod -Method Get -Uri "https://api.github.com/repos/${env:GITHUB_REPOSITORY}/releases/tags/${env:GITHUB_REF_NAME}" -Headers @{ Authorization = "token $env:GITHUB_TOKEN" }
          Write-Output "Release Object: $($release | ConvertTo-Json -Depth 3)"
          $uploadUrl = $release.upload_url
          echo "::set-output name=url::$uploadUrl"
        shell: pwsh
      # - name: Upload releases/Zeungine.exe
      #   if: runner.os == 'Windows'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.get_upload_url_windows.outputs.url}}
      #     asset_path: ./releases/Zeungine.exe
      #     asset_name: Zeungine.exe
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/Zeungine-debug.exe
      #   if: runner.os == 'Windows'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.get_upload_url_windows.outputs.url}}
      #     asset_path: ./releases/Zeungine-debug.exe
      #     asset_name: Zeungine-debug.exe
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/Zeungine-debug-static.exe
      #   if: runner.os == 'Windows'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.get_upload_url_windows.outputs.url}}
      #     asset_path: ./releases/Zeungine-debug-static.exe
      #     asset_name: Zeungine-debug-static.exe
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/ZeungineDependencies.exe
      #   if: runner.os == 'Windows'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.get_upload_url_windows.outputs.url}}
      #     asset_path: ./releases/ZeungineDependencies.exe
      #     asset_name: ZeungineDependencies.exe
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/ZeungineDependencies-debug.exe
      #   if: runner.os == 'Windows'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.get_upload_url_windows.outputs.url}}
      #     asset_path: ./releases/ZeungineDependencies-debug.exe
      #     asset_name: ZeungineDependencies-debug.exe
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/ZeungineDependencies-debug-static.exe
      #   if: runner.os == 'Windows'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.get_upload_url_windows.outputs.url}}
      #     asset_path: ./releases/ZeungineDependencies-debug-static.exe
      #     asset_name: ZeungineDependencies-debug-static.exe
      #     asset_content_type: application/octet-stream
      # - name: Upload releases/ZeungineHeaders.exe
      #   if: runner.os == 'Windows'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   with:
      #     upload_url: ${{steps.get_upload_url_windows.outputs.url}}
      #     asset_path: ./releases/ZeungineHeaders.exe
      #     asset_name: ZeungineHeaders.exe
      #     asset_content_type: application/octet-stream
      - name: Upload auto-install.bat
        if: runner.os == 'Windows'
        id: upload_windows_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.get_upload_url_windows.outputs.url}}
          asset_path: ./auto-install.bat
          asset_name: auto-install.bat
          asset_content_type: application/octet-stream
