name: Release on Tag
on:
  push:
    tags:
      - 'v*.*.*.*'
permissions:
  contents: write
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies on Linux
        if: runner.os == 'Linux'
        run: sudo apt install nasm libx11-dev uuid-dev libglx-dev libgl1-mesa-dev libxfixes-dev libxrandr-dev libxkbcommon-dev libdrm-dev ninja-build
        shell: bash

      - name: Install Dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install dos2unix
          C:\\msys64\\msys2_shell.cmd -defterm -no-start -mingw64 -here -use-full-path -c "pacman -S --noconfirm make diffutils"
        shell: bash

      # - name: Build Package on Linux
      #   if: runner.os == 'Linux'
      #   run: ./unx-package.sh 0
      #   shell: bash

      # - name: Build Package on Windows
      #   if: runner.os == 'Windows'
      #   run: .\win-package.bat 8
      #   shell: cmd

      - name: Compile Release Notes
        if: runner.os == 'Linux'
        id: notes
        run: |
          PREV_HASH=$(git rev-list --tags --skip 1 --max-count 1)
          PREV_TAG=$(git describe --abbrev=0 --tags $PREV_HASH || echo "")
          if [ -z "$PREV_TAG" ]
          then
            PREV_TAG=$(git rev-list --max-parents=0 HEAD)
            echo "Using first commit as previous tag: $PREV_TAG"
          fi
          GITHUB_SHA=${GITHUB_SHA:-$(git rev-parse HEAD)}  # Ensure GITHUB_SHA is set if missing
          echo "::set-output name=body::$(git log $PREV_TAG..$GITHUB_SHA --pretty=format:'%h %s')"
        shell: bash
      
      - name: Create Release
        if: runner.os == 'Linux'
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.notes.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # artifacts["releases/zeungine.deb"]="application/vnd.debian.binary-package"
          # artifacts["releases/zeungine-debug.deb"]="application/vnd.debian.binary-package"
          # artifacts["releases/zeungine-static.deb"]="application/vnd.debian.binary-package"
          # artifacts["releases/zeungine-debug-static.deb"]="application/vnd.debian.binary-package"
          # artifacts["releases/zeungine-dependencies.deb"]="application/vnd.debian.binary-package"
          # artifacts["releases/zeungine-dependencies-debug.deb"]="application/vnd.debian.binary-package"
          # artifacts["releases/zeungine-dependencies-debug-static.deb"]="application/vnd.debian.binary-package"
          # artifacts["releases/zeungine-headers.deb"]="application/vnd.debian.binary-package"
      - name: Upload Assets Linux
        if: runner.os == 'Linux'
        id: upload_linux_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./deb-auto-install.sh
          asset_name: deb-auto-install.sh
          asset_content_type: application/octet-stream

      - name: Get uploadUrl for Windows
        if: runner.os == 'Windows'
        id: get_upload_url_windows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $ErrorActionPreference = "Stop"
          $release = Invoke-RestMethod -Method Get -Uri "https://api.github.com/repos/${env:GITHUB_REPOSITORY}/releases/tags/${env:GITHUB_REF_NAME}" -Headers @{ Authorization = "token $env:GITHUB_TOKEN" }
          Write-Output "Release Object: $($release | ConvertTo-Json -Depth 3)"
          $uploadUrl = $release.upload_url
          echo "::set-output name=url::$uploadUrl"
        shell: pwsh

            # "releases/Zeungine.exe" = "application/octet-stream"
            # "releases/Zeungine-debug.exe" = "application/octet-stream"
            # "releases/Zeungine-debug-static.exe" = "application/octet-stream"
            # "releases/ZeungineDependencies.exe" = "application/octet-stream"
            # "releases/ZeungineDependencies-debug.exe" = "application/octet-stream"
            # "releases/ZeungineDependencies-debug-static.exe" = "application/octet-stream"
            # "releases/ZeungineHeaders.exe" = "application/octet-stream"
            # "auto-install.bat" = "application/octet-stream"
            # get_upload_url_windows
      - name: Upload Release Asset
        if: runner.os == 'Windows'
        id: upload_windows_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_upload_url_windows.outputs.url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./auto-install.bat
          asset_name: auto-install.bat
          asset_content_type: application/octet-stream
